apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.containerName }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.backend.containerName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.containerName }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.backend.configMapName }}
            - secretRef:
                name: {{ .Values.backend.secretName }}
