apiVersion: v1
kind: Service
metadata:
  name: pump-watch-backend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: pump-watch-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
