apiVersion: v1
kind: Service
metadata:
  name: pump-watch-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: pump-watch-frontend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
