apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.containerName }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.frontend.containerName }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.containerName }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: BROWSER
              value: "none"
          envFrom:
            - configMapRef:
                name: {{ .Values.frontend.configMapName }}
