apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pump-watch-frontend-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: {{ .Values.frontend.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.containerName }}
                port:
                  number: {{ .Values.frontend.port }}
