apiVersion: v1
kind: Service
metadata:
  name: pump-watch-flask
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: pump-watch-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
