apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.containerName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.mysql.containerName }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
