apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.mysql.username | b64enc }}
  DB_PASSWORD: {{ .Values.mysql.password | b64enc }}
  SECRET: {{ "yfoyfyitdotkuyfouyoyf" | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.flask.secretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  GOOGLE_API_KEY: {{ "AIzaSyCYq-AavDWA5RhEoZ0lXBOfWzzOCf8u5dA" | b64enc }}
